
#유저 목록 조회
GET http://localhost:3020/users
###
#유저 사진 목록조회
GET http://localhost:3020/users/photos
###
#단일 유저 조회
GET http://localhost:3020/users/broth59
###
#단일 유저 사진 조회
GET http://localhost:3020/users/broth59/photos


###
#유저 등록
POST http://localhost:3020/users
Content-Type: application/json

{
	"id": "broth59",
	"email": "broth59@naver.com",
	"photo": {
		"image_path" : "s8"
	}
}

###
#유저 삭제
DELETE http://localhost:3020/users
Content-Type: application/json

{
	"id": "broth60",
	"email": "broth59@naver.com"
}
###
